# Generated by Django 4.2.26 on 2026-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisemandatoryfund',
            name='form_type',
            field=models.CharField(blank=True, help_text='existing/new', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enterprisesupport',
            name='form_type',
            field=models.CharField(blank=True, help_text='existing/new', max_length=20, null=True),
        ),
    ]
