# Generated by Django 4.2.26 on 2026-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epSakhi', '0002_enterprisemandatoryfund_form_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriselicenses',
            name='license_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
